version: '3.7'

services:         
  communicationportal.api:
    image: player.api:latest
    container_name: 'PlayerAPI'
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "5193:80"
        - "7118:443"
    environment:
        ASPNETCORE_ConnectionStrings__Database: 'Server=localhost; Port=3306; Database=nbaplayerdb; Uid=root; Pwd=admin; SslMode=Preferred;UseXaTransactions=false;'

  mysql_db:
    image: 'mysql/mysql-server:latest'
    container_name: 'Players-MYSQL'
    restart: always
    ports: 
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: nbaplayerdb
        MYSQL_USER: root
        MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: